/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface Notice {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'date' : Time,
}
export interface Photo {
  'id' : bigint,
  'title' : string,
  'image' : ExternalBlob,
}
export interface StudyMaterial {
  'id' : bigint,
  'title' : string,
  'subject' : string,
  'file' : ExternalBlob,
  'description' : string,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VisitorEntry {
  'id' : bigint,
  'institution' : string,
  'name' : string,
  'visitedAt' : Time,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createNotice' : ActorMethod<[string, string], undefined>,
  'deleteNotice' : ActorMethod<[bigint], undefined>,
  'deletePhoto' : ActorMethod<[bigint], undefined>,
  'deleteStudyMaterial' : ActorMethod<[bigint], undefined>,
  'getAllNotices' : ActorMethod<[], Array<Notice>>,
  'getAllPhotos' : ActorMethod<[], Array<Photo>>,
  'getAllStudyMaterials' : ActorMethod<[], Array<StudyMaterial>>,
  'getAllVisitors' : ActorMethod<[], Array<VisitorEntry>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getNotice' : ActorMethod<[bigint], [] | [Notice]>,
  'getPhoto' : ActorMethod<[bigint], [] | [Photo]>,
  'getStudyMaterial' : ActorMethod<[bigint], [] | [StudyMaterial]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVisitorCount' : ActorMethod<[], bigint>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'recordVisit' : ActorMethod<[], bigint>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'signInVisitor' : ActorMethod<[string, string], VisitorEntry>,
  'uploadPhoto' : ActorMethod<[string, ExternalBlob], undefined>,
  'uploadStudyMaterial' : ActorMethod<
    [string, string, string, ExternalBlob],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];